#!/usr/bin/env python3
import rospy, rosnode
from std_srvs.srv import Empty
from gazebo_msgs.msg import ModelStates
from gazebo_msgs.srv import DeleteModel

NODES_KEEP = ['/rosout', '/gazebo_gui', '/gazebo', '/mapper']
MODELS_KEEP = ['ground_plane']

if __name__ == '__main__':
	rospy.init_node('killer')
	NODES_KEEP.append(rospy.get_name())

	try:
		print('Killing certain nodes...')
		for n in rosnode.get_node_names():
			if n not in NODES_KEEP:
				print('Killing', n)
				rosnode.kill_nodes([n])

		print('Deleting certain models...')
		rospy.ServiceProxy('/gazebo/unpause_physics', Empty)()
		for m in rospy.wait_for_message('/gazebo/model_states', ModelStates, timeout=1.0).name:
			if m not in MODELS_KEEP:
				print('Deleting', m)
				rospy.ServiceProxy('/gazebo/delete_model', DeleteModel)(m)
		
		# can't reset simulation bc time moves backwards
	except Exception as e:
		print('FAILED!!! Just restart everything :(')
		print('Error message:', e)





	