<?xml version="1.0" ?>
<robot name="box" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- TODO adjust parameters -->
	<xacro:property name="len" value="0.25"/>
	<xacro:property name="mass" value="1"/>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${len} ${len} ${len}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${len} ${len} ${len}"/>
			</geometry>
		</collision>

		<inertial>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia
        		ixx="${1/6*mass*len*len}" ixy="0.0" ixz="0.0"
        		iyy="${1/6*mass*len*len}" iyz="0.0"
        		izz="${1/6*mass*len*len}"/>
		</inertial>
	</link>

<!-- TODO change friction -->
	<gazebo reference="base_link">
		<mu1>0.1</mu1>
		<mu2>0.1</mu2>
		<material>Gazebo/Blue</material>
	</gazebo>
</robot>
