<?xml version="1.0" ?>
<robot name="box" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="len" value="0.249"/>
	<xacro:property name="mass" value="0.5"/>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${len} ${len} ${len}"/>
			</geometry>
		</visual>

		<!-- Collision bitmasks not parsed properly currently -->
		<!-- So here's the janky workaround, actually cleaner -->

		<inertial>
			<origin xyz="0 0 ${len/2}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia
        		ixx="${1/6*mass*len*len}" ixy="0.0" ixz="0.0"
        		iyy="${1/6*mass*len*len}" iyz="0.0"
        		izz="${1/6*mass*len*len}"/>
		</inertial>
	</link>

	<gazebo reference="base_link">
		<visual>
			<plugin name="invisible" filename="libmouse_gazebo.so"/>
		</visual>
		<turnGravityOff>true</turnGravityOff>
		<material>Gazebo/GreenTransparent</material>
	</gazebo>
</robot>
